package com.scaso.drclawapp.data.websocket

// ---------------------------------------------------------------------
// AUTO-GENERATED by ironjaw codegen -- 2026-03-20T15:35:38Z
// Do not edit manually. Regenerate with:
//   cd ironjaw/tools/codegen
//   python extract_schema.py | python generate_kotlin.py > IronjawProtocol.kt
// ---------------------------------------------------------------------

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

/**
 * Ironjaw RPC method constants and typed request builders.
 * Generated from 85 methods across 24 categories.
 */
object IronjawProtocol {

    // -- Method Constants -------------------------------------------

    // backup
    const val BACKUP_CREATE = "backup.create"

    // brain
    const val BRAIN_REMEMBER = "brain.remember"
    const val BRAIN_RECALL = "brain.recall"
    const val BRAIN_FORGET = "brain.forget"
    const val BRAIN_IMPORT = "brain.import"
    const val BRAIN_STATUS = "brain.status"
    const val BRAIN_RELOAD = "brain.reload"
    const val BRAIN_MEMORIES = "brain.memories"
    const val BRAIN_CONSOLIDATE = "brain.consolidate"
    const val BRAIN_TIMELINE = "brain.timeline"
    const val BRAIN_SUMMARIES = "brain.summaries"
    const val BRAIN_CONTEXT_SET = "brain.context.set"
    const val BRAIN_CONTEXT_LOAD = "brain.context.load"
    const val BRAIN_CONTEXT_LIST = "brain.context.list"
    const val BRAIN_CONTEXT_DELETE = "brain.context.delete"
    const val BRAIN_CONTEXT_PEEK = "brain.context.peek"

    // cc
    const val CC_SESSIONS = "cc.sessions"
    const val CC_SESSION_GET = "cc.session.get"
    const val CC_HISTORY = "cc.history"
    const val CC_CHAT = "cc.chat"
    const val CC_CHAT_ABORT = "cc.chat.abort"
    const val CC_SESSION_CREATE = "cc.session.create"
    const val CC_ATTACH = "cc.attach"
    const val CC_DETACH = "cc.detach"

    // ccbridge
    const val CCBRIDGE_SESSIONS = "ccbridge.sessions"
    const val CCBRIDGE_SESSIONS_RENAME = "ccbridge.sessions.rename"
    const val CCBRIDGE_CHAT = "ccbridge.chat"

    // chat
    const val CHAT_SEND = "chat.send"
    const val CHAT_HISTORY = "chat.history"
    const val CHAT_ABORT = "chat.abort"
    const val CHAT_INJECT = "chat.inject"

    // chronicle
    const val CHRONICLE_SESSIONS = "chronicle.sessions"
    const val CHRONICLE_SESSION = "chronicle.session"
    const val CHRONICLE_SEARCH = "chronicle.search"
    const val CHRONICLE_TOPICS = "chronicle.topics"
    const val CHRONICLE_INSIGHTS = "chronicle.insights"
    const val CHRONICLE_STATS = "chronicle.stats"
    const val CHRONICLE_TIMELINE = "chronicle.timeline"
    const val CHRONICLE_ENRICH = "chronicle.enrich"

    // command
    const val COMMAND_SESSIONS = "command.sessions"
    const val COMMAND_SESSION_GET = "command.session.get"
    const val COMMAND_SESSION_ACTION = "command.session.action"
    const val COMMAND_USAGE_SUMMARY = "command.usage.summary"
    const val COMMAND_USAGE_BY_ROLE = "command.usage.by_role"

    // device
    const val DEVICE_LIST = "device.list"
    const val DEVICE_CMD = "device.cmd"
    const val DEVICE_PAIR_REQUEST = "device.pair.request"
    const val DEVICE_PAIR_CONFIRM = "device.pair.confirm"
    const val DEVICE_PAIR_REVOKE = "device.pair.revoke"

    // agent
    const val AGENT_FORK = "agent.fork"

    // export
    const val EXPORT_CONVERSATIONS = "export.conversations"
    const val EXPORT_BRAIN = "export.brain"

    // file
    const val FILE_GET = "file.get"

    // gateway
    const val GATEWAY_MODEL = "gateway.model"
    const val GATEWAY_RESTART = "gateway.restart"

    // infra
    const val INFRA_STATUS = "infra.status"

    // model
    const val MODEL_LIST = "model.list"
    const val MODEL_AVAILABLE = "model.available"
    const val MODEL_LLM = "model.llm"
    const val MODEL_SWITCH = "model.switch"
    const val MODEL_SESSION = "model.session"
    const val MODEL_PERF = "model.perf"

    // notify
    const val NOTIFY_SEND = "notify.send"

    // project
    const val PROJECT_STATUS = "project.status"

    // role
    const val ROLE_LIST = "role.list"
    const val ROLE_SWITCH = "role.switch"
    const val ROLE_ACTIVE = "role.active"
    const val ROLE_PRESET_APPLY = "role.preset.apply"

    // schedule
    const val SCHEDULE_LIST = "schedule.list"
    const val SCHEDULE_CREATE = "schedule.create"
    const val SCHEDULE_DELETE = "schedule.delete"
    const val SCHEDULE_TOGGLE = "schedule.toggle"

    // session
    const val SESSION_LIST = "session.list"
    const val SESSION_GET = "session.get"
    const val SESSION_CREATE = "session.create"
    const val SESSION_SWITCH = "session.switch"
    const val SESSION_SET_CWD = "session.set_cwd"
    const val SESSION_DELETE = "session.delete"
    const val SESSION_RENAME = "session.rename"

    // sessions
    const val SESSIONS_PATCH = "sessions.patch"
    const val SESSIONS_DELETE = "sessions.delete"
    const val SESSIONS_PREVIEW = "sessions.preview"

    // system
    const val SYSTEM_RESOURCES = "system.resources"

    // tools
    const val TOOLS_LIST = "tools.list"
    const val TOOLS_EXECUTE = "tools.execute"

    // tts
    const val TTS_GENERATE = "tts.generate"
    const val TTS_VOICES = "tts.voices"

    // voice
    const val VOICE_START = "voice.start"
    const val VOICE_STOP = "voice.stop"
    const val VOICE_TTS = "voice.tts"

    // workflow
    const val WORKFLOW_CREATE = "workflow.create"
    const val WORKFLOW_STATUS = "workflow.status"
    const val WORKFLOW_CANCEL = "workflow.cancel"
    const val WORKFLOW_APPROVE = "workflow.approve"

    // -- Tier Info ----------------------------------------------------

    /** Permission tier for each method (auto, notify, confirm, multiconfirm). */
    val tiers: Map<String, String> = mapOf(
        AGENT_FORK to "confirm",
        CHAT_SEND to "unknown",
        CHAT_HISTORY to "unknown",
        CHAT_ABORT to "unknown",
        CHAT_INJECT to "unknown",
        MODEL_LIST to "unknown",
        MODEL_AVAILABLE to "unknown",
        GATEWAY_MODEL to "unknown",
        SESSION_LIST to "unknown",
        SESSION_GET to "unknown",
        SESSION_CREATE to "unknown",
        SESSION_SWITCH to "unknown",
        SESSION_SET_CWD to "confirm",
        SESSION_DELETE to "unknown",
        SESSION_RENAME to "unknown",
        TOOLS_LIST to "unknown",
        TOOLS_EXECUTE to "unknown",
        BRAIN_REMEMBER to "unknown",
        BRAIN_RECALL to "unknown",
        BRAIN_FORGET to "unknown",
        BRAIN_IMPORT to "unknown",
        BRAIN_STATUS to "unknown",
        BRAIN_RELOAD to "unknown",
        BRAIN_MEMORIES to "unknown",
        BRAIN_CONSOLIDATE to "unknown",
        BRAIN_TIMELINE to "unknown",
        BRAIN_SUMMARIES to "unknown",
        BRAIN_CONTEXT_SET to "unknown",
        BRAIN_CONTEXT_LOAD to "unknown",
        BRAIN_CONTEXT_LIST to "unknown",
        BRAIN_CONTEXT_DELETE to "unknown",
        BRAIN_CONTEXT_PEEK to "unknown",
        SCHEDULE_LIST to "unknown",
        SCHEDULE_CREATE to "unknown",
        SCHEDULE_DELETE to "unknown",
        SCHEDULE_TOGGLE to "unknown",
        WORKFLOW_CREATE to "unknown",
        WORKFLOW_STATUS to "unknown",
        WORKFLOW_CANCEL to "unknown",
        WORKFLOW_APPROVE to "unknown",
        VOICE_START to "unknown",
        VOICE_STOP to "unknown",
        VOICE_TTS to "unknown",
        TTS_GENERATE to "unknown",
        TTS_VOICES to "unknown",
        DEVICE_LIST to "unknown",
        DEVICE_CMD to "unknown",
        NOTIFY_SEND to "unknown",
        EXPORT_CONVERSATIONS to "unknown",
        EXPORT_BRAIN to "unknown",
        INFRA_STATUS to "unknown",
        BACKUP_CREATE to "unknown",
        CCBRIDGE_SESSIONS to "unknown",
        CCBRIDGE_SESSIONS_RENAME to "unknown",
        CCBRIDGE_CHAT to "unknown",
        CC_SESSIONS to "unknown",
        CC_SESSION_GET to "unknown",
        CC_HISTORY to "unknown",
        CC_CHAT to "unknown",
        CC_CHAT_ABORT to "unknown",
        CC_SESSION_CREATE to "unknown",
        CC_ATTACH to "unknown",
        CC_DETACH to "unknown",
        CHRONICLE_SESSIONS to "unknown",
        CHRONICLE_SESSION to "unknown",
        CHRONICLE_SEARCH to "unknown",
        CHRONICLE_TOPICS to "unknown",
        CHRONICLE_INSIGHTS to "unknown",
        CHRONICLE_STATS to "unknown",
        CHRONICLE_TIMELINE to "unknown",
        PROJECT_STATUS to "unknown",
        FILE_GET to "unknown",
        MODEL_LLM to "unknown",
        MODEL_SWITCH to "unknown",
        ROLE_LIST to "unknown",
        ROLE_SWITCH to "unknown",
        ROLE_ACTIVE to "unknown",
        MODEL_SESSION to "unknown",
        ROLE_PRESET_APPLY to "unknown",
        GATEWAY_RESTART to "unknown",
        CHRONICLE_ENRICH to "unknown",
        SESSIONS_PATCH to "unknown",
        SESSIONS_DELETE to "unknown",
        SESSIONS_PREVIEW to "unknown",
        COMMAND_SESSIONS to "unknown",
        COMMAND_SESSION_GET to "unknown",
        COMMAND_SESSION_ACTION to "unknown",
        COMMAND_USAGE_SUMMARY to "unknown",
        COMMAND_USAGE_BY_ROLE to "unknown",
        SYSTEM_RESOURCES to "unknown",
        DEVICE_PAIR_REQUEST to "unknown",
        DEVICE_PAIR_CONFIRM to "unknown",
        DEVICE_PAIR_REVOKE to "unknown",
        MODEL_PERF to "unknown",
    )

    // -- Request Builders ---------------------------------------------

    /** Build params for `cc.attach` RPC. */
    fun ccAttachParams(sessionId: String): JsonElement = buildJsonObject {
        put("sessionId", sessionId)
    }

    /** Build params for `cc.chat` RPC. */
    fun ccChatParams(sessionId: String?, message: String, thinkingLevel: String? = null): JsonElement = buildJsonObject {
        sessionId?.let { put("sessionId", it) }
        put("message", message)
        thinkingLevel?.let { put("thinkingLevel", it) }
    }

    /** Build params for `cc.chat.abort` RPC. */
    fun ccChatAbortParams(sessionId: String): JsonElement = buildJsonObject {
        put("sessionId", sessionId)
    }

    /** Build params for `cc.detach` RPC. */
    fun ccDetachParams(sessionId: String): JsonElement = buildJsonObject {
        put("sessionId", sessionId)
    }

    /** Build params for `cc.history` RPC. */
    fun ccHistoryParams(sessionId: String, limit: Int? = null): JsonElement = buildJsonObject {
        put("sessionId", sessionId)
        limit?.let { put("limit", it) }
    }

    /** Build params for `cc.session.create` RPC. */
    fun ccSessionCreateParams(cwd: String? = null, role: String? = null, model: String? = null, project: String? = null): JsonElement = buildJsonObject {
        cwd?.let { put("cwd", it) }
        role?.let { put("role", it) }
        model?.let { put("model", it) }
        project?.let { put("project", it) }
    }

    /** Build params for `cc.session.get` RPC. */
    fun ccSessionGetParams(sessionId: String): JsonElement = buildJsonObject {
        put("sessionId", sessionId)
    }

    /** Build params for `cc.sessions` RPC. */
    fun ccSessionsParams(): JsonElement? = null

    /** Build params for `session.set_cwd` RPC. */
    fun sessionSetCwdParams(sessionId: String, path: String?): JsonElement = buildJsonObject {
        put("session_id", sessionId)
        path?.let { put("path", it) }
    }

    /** Build params for `agent.fork` RPC. */
    fun agentForkParams(
        parentSessionId: String,
        task: String,
        inheritTools: Boolean = true,
        inheritBrainContext: Boolean = false,
    ): JsonElement = buildJsonObject {
        put("parent_session_id", parentSessionId)
        put("task", task)
        put("inherit_tools", inheritTools)
        put("inherit_brain_context", inheritBrainContext)
    }

    /** Build params for `chat.abort` RPC. */
    fun chatAbortParams(runId: String? = null): JsonElement = buildJsonObject {
        runId?.let { put("runId", it) }
    }

    /** Build params for `chat.history` RPC. */
    fun chatHistoryParams(limit: Int? = null): JsonElement = buildJsonObject {
        limit?.let { put("limit", it) }
    }

    /** Build params for `chat.send` RPC. */
    fun chatSendParams(message: String): JsonElement = buildJsonObject {
        put("message", message)
    }

    /** Build params for `device.list` RPC. */
    fun deviceListParams(): JsonElement? = null

    /** Build params for `infra.status` RPC. */
    fun infraStatusParams(): JsonElement? = null

    /** Build params for `model.list` RPC. */
    fun modelListParams(): JsonElement? = null

    /** Build params for `model.status` RPC. */
    fun modelStatusParams(): JsonElement? = null

    /** Build params for `model.switch` RPC. */
    fun modelSwitchParams(model: String): JsonElement = buildJsonObject {
        put("model", model)
    }

    /** Build params for `tts.generate` RPC. */
    fun ttsGenerateParams(text: String, voice: String? = null): JsonElement = buildJsonObject {
        put("text", text)
        voice?.let { put("voice", it) }
    }

    /** Build params for `tts.voices` RPC. */
    fun ttsVoicesParams(): JsonElement? = null

    // -- Category Grouping --------------------------------------------

    val categories: Map<String, List<String>> = mapOf(
        "agent" to listOf(AGENT_FORK),
        "backup" to listOf(BACKUP_CREATE),
        "brain" to listOf(BRAIN_REMEMBER, BRAIN_RECALL, BRAIN_FORGET, BRAIN_IMPORT, BRAIN_STATUS, BRAIN_RELOAD, BRAIN_MEMORIES, BRAIN_CONSOLIDATE, BRAIN_TIMELINE, BRAIN_SUMMARIES, BRAIN_CONTEXT_SET, BRAIN_CONTEXT_LOAD, BRAIN_CONTEXT_LIST, BRAIN_CONTEXT_DELETE, BRAIN_CONTEXT_PEEK),
        "cc" to listOf(CC_SESSIONS, CC_SESSION_GET, CC_HISTORY, CC_CHAT, CC_CHAT_ABORT, CC_SESSION_CREATE, CC_ATTACH, CC_DETACH),
        "ccbridge" to listOf(CCBRIDGE_SESSIONS, CCBRIDGE_SESSIONS_RENAME, CCBRIDGE_CHAT),
        "chat" to listOf(CHAT_SEND, CHAT_HISTORY, CHAT_ABORT, CHAT_INJECT),
        "chronicle" to listOf(CHRONICLE_SESSIONS, CHRONICLE_SESSION, CHRONICLE_SEARCH, CHRONICLE_TOPICS, CHRONICLE_INSIGHTS, CHRONICLE_STATS, CHRONICLE_TIMELINE, CHRONICLE_ENRICH),
        "command" to listOf(COMMAND_SESSIONS, COMMAND_SESSION_GET, COMMAND_SESSION_ACTION, COMMAND_USAGE_SUMMARY, COMMAND_USAGE_BY_ROLE),
        "device" to listOf(DEVICE_LIST, DEVICE_CMD, DEVICE_PAIR_REQUEST, DEVICE_PAIR_CONFIRM, DEVICE_PAIR_REVOKE),
        "export" to listOf(EXPORT_CONVERSATIONS, EXPORT_BRAIN),
        "file" to listOf(FILE_GET),
        "gateway" to listOf(GATEWAY_MODEL, GATEWAY_RESTART),
        "infra" to listOf(INFRA_STATUS),
        "model" to listOf(MODEL_LIST, MODEL_AVAILABLE, MODEL_LLM, MODEL_SWITCH, MODEL_SESSION, MODEL_PERF),
        "notify" to listOf(NOTIFY_SEND),
        "project" to listOf(PROJECT_STATUS),
        "role" to listOf(ROLE_LIST, ROLE_SWITCH, ROLE_ACTIVE, ROLE_PRESET_APPLY),
        "schedule" to listOf(SCHEDULE_LIST, SCHEDULE_CREATE, SCHEDULE_DELETE, SCHEDULE_TOGGLE),
        "session" to listOf(SESSION_LIST, SESSION_GET, SESSION_CREATE, SESSION_SWITCH, SESSION_SET_CWD, SESSION_DELETE, SESSION_RENAME),
        "sessions" to listOf(SESSIONS_PATCH, SESSIONS_DELETE, SESSIONS_PREVIEW),
        "system" to listOf(SYSTEM_RESOURCES),
        "tools" to listOf(TOOLS_LIST, TOOLS_EXECUTE),
        "tts" to listOf(TTS_GENERATE, TTS_VOICES),
        "voice" to listOf(VOICE_START, VOICE_STOP, VOICE_TTS),
        "workflow" to listOf(WORKFLOW_CREATE, WORKFLOW_STATUS, WORKFLOW_CANCEL, WORKFLOW_APPROVE),
    )
}

